/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
// int printf(const char *format, ...);
// void *malloc(size_t size);
// int puts(const char *s);
// int __gmon_start__(void); weak
// void exit(int status);
void sub_80483C0();
signed int sub_80483D0();
signed int sub_8048440();
int sub_8048460();
int __cdecl check(foreststructure *a1, _BYTE *a2, _BYTE *a3); // idb
int __cdecl check2(foreststructure *a1, _BYTE *a2, char a3); // idb
foreststructure *__cdecl nest(_DWORD *a1, char a2);
int __cdecl sub_80486A4(int a1);
foreststructure *__cdecl get_third_argument(int a1);
int __cdecl main(int argc, char **argv); // idb
void init(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*off_8049AE8[2])() = { &sub_8048460, &sub_8048440 }; // weak
int (*off_8049AEC)() = &sub_8048440; // weak
char *off_8049C0C = "yuoteavpxqgrlsdhwfjkzi_cmbn"; // weak
char byte_8049C10; // weak
_UNKNOWN unk_8049C13; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (080482F4) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax@1

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (void *)__gmon_start__();
  return result;
}
// 8048360: using guessed type int __gmon_start__(void);

//----- (08048390) --------------------------------------------------------
#error "8048393: positive sp value has been found (funcsize=2)"

//----- (080483C0) --------------------------------------------------------
void sub_80483C0()
{
  ;
}

//----- (080483D0) --------------------------------------------------------
signed int sub_80483D0()
{
  signed int result; // eax@1

  result = &unk_8049C13 - (_UNKNOWN *)&byte_8049C10;
  if ( (unsigned int)(&unk_8049C13 - (_UNKNOWN *)&byte_8049C10) > 6 )
    result = 0;
  return result;
}
// 80483D0: could not find valid save-restore pair for ebp
// 8049C10: using guessed type char byte_8049C10;

//----- (08048440) --------------------------------------------------------
signed int sub_8048440()
{
  signed int result; // eax@2

  if ( !byte_8049C10 )
  {
    result = sub_80483D0();
    byte_8049C10 = 1;
  }
  return result;
}
// 8048440: could not find valid save-restore pair for ebp
// 8049C10: using guessed type char byte_8049C10;

//----- (08048460) --------------------------------------------------------
int sub_8048460()
{
  return 0;
}
// 8048460: could not find valid save-restore pair for ebp

//----- (0804848B) --------------------------------------------------------
int __cdecl check(foreststructure *a1, _BYTE *a2, _BYTE *a3)
{
  int result; // eax@4
  char *v4; // [sp+4h] [bp-14h]@5
  _BYTE *v5; // [sp+8h] [bp-10h]@5
  signed int v6; // [sp+Ch] [bp-Ch]@5

  if ( a1 && a2 && a3 )
  {
    v6 = 1;
    v5 = a2;
    v4 = a3;
    while ( *v5 && *v4 )
    {
      v6 &= check2(a1, v5, *v4++);
      while ( *v5 == 'L' || *v5 == 'R' )
        ++v5;
      ++v5;
    }
    result = (*v5 == 0 && *v4 == 0) & (unsigned __int8)v6;
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (08048539) --------------------------------------------------------
int __cdecl check2(foreststructure *a1, _BYTE *a2, char a3)
{
  int result; // eax@3

  if ( a1 && *a2 )
  {
    if ( BYTE2(a1[1].first) == a3 )
    {
      if ( *a2 == 'D' )
        result = BYTE2(a1[1].first) == a3;
      else
        result = 0;
    }
    else if ( SBYTE2(a1[1].first) <= a3 )
    {
      if ( *a2 == 'R' )
        result = check2(*(foreststructure **)&a1->second, a2 + 1, a3);
      else
        result = 0;
    }
    else if ( *a2 == 'L' )
    {
      result = check2((foreststructure *)a1->first, a2 + 1, a3);
    }
    else
    {
      result = 0;
    }
  }
  else
  {
    result = 0;
  }
  return result;
}

//----- (08048607) --------------------------------------------------------
foreststructure *__cdecl nest(_DWORD *a1, char a2)
{
  foreststructure *result; // eax@2

  if ( a1 )
  {
    if ( *((_BYTE *)a1 + 8) >= a2 )
    {
      *a1 = nest((_DWORD *)*a1, a2);
      result = (foreststructure *)a1;
    }
    else
    {
      a1[1] = nest((_DWORD *)a1[1], a2);
      result = (foreststructure *)a1;
    }
  }
  else
  {
    result = (foreststructure *)malloc(12u);
    result->first = 0;
    *(_DWORD *)&result->second = 0;
    BYTE2(result[1].first) = a2;
  }
  return result;
}

//----- (080486A4) --------------------------------------------------------
int __cdecl sub_80486A4(int a1)
{
  int result; // eax@2

  if ( a1 )
  {
    sub_80486A4(*(_DWORD *)a1);
    printf("%c ", *(_BYTE *)(a1 + 8));
    result = sub_80486A4(*(_DWORD *)(a1 + 4));
  }
  return result;
}

//----- (080486F0) --------------------------------------------------------
foreststructure *__cdecl get_third_argument(int a1)
{
  int i; // [sp+8h] [bp-10h]@1
  foreststructure *v3; // [sp+Ch] [bp-Ch]@1

  v3 = 0;
  for ( i = 0; *(_BYTE *)(a1 + i); ++i )        // "yuoteavpxqgrlsdhwfjkzi_cmbn"
    v3 = nest(v3, *(_BYTE *)(a1 + i));
  return v3;
}

//----- (0804873E) --------------------------------------------------------
int __cdecl main(int argc, char **argv)
{
  foreststructure *v3; // [sp+4h] [bp-Ch]@1

  v3 = get_third_argument((int)off_8049C0C);    // "yuoteavpxqgrlsdhwfjkzi_cmbn"
  if ( argc != 3 )
  {
    puts("You have the wrong number of arguments for this forest.");
    printf("%s [password] [string]\n", *argv);
    exit(1);
  }
  if ( check(v3, argv[2], argv[1]) )
    puts("You did it! Submit the input as the flag");
  else
    puts("Nope.");
  return 0;
}
// 8049C0C: using guessed type char *off_8049C0C;

//----- (08048800) --------------------------------------------------------
void init(void)
{
  int v0; // edi@1
  signed int v1; // esi@1

  v0 = 0;
  init_proc();
  v1 = &off_8049AEC - off_8049AE8;
  if ( v1 )
  {
    do
      off_8049AE8[v0++]();
    while ( v0 != v1 );
  }
}
// 8049AE8: using guessed type int (*off_8049AE8[2])();
// 8049AEC: using guessed type int (*off_8049AEC)();

//----- (08048874) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 14 function(s)"
